In [1]:
from IPython.core.display import HTML

def _set_css_style(css_file_path):
   """
   Read the custom CSS file and load it into Jupyter.
   Pass the file path to the CSS file.
   """

   styles = open(css_file_path, "r").read()
   s = '<style>%s</style>' % styles     
   return HTML(s)

_set_css_style('rise.css')

In [ ]:
df = pd.read_csv('../files/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2014.csv.gz', usecols=[3,7,10,14,15,16,17,29,30,35])
df.to_csv('../files/SPARCS_2014_compressed.csv.gz', index=False)

# More tabular data with `pandas`

<a href="?print-pdf">print view</a><br>
<a href="lecture-11-pandas2.ipynb">notebook</a>

* Accessing data in `pandas` 
* Data processing and rearrangement
* Combining data frames

## SPARCS medical record data

Download this (and, optionally, unzip it):
https://mscbio2025-2025.github.io/files/SPARCS_2014_compressed.csv.gz

More information here: https://navigator.med.nyu.edu/ace/sparcs/

## Analyzing the data with `pandas`

**Note:** This is a *large* dataset, so we have already dropped a number of columns and are reading the data in compressed format (the uncompressed file is 6x larger!)

In [2]:
import pandas as pd
data = pd.read_csv('../files/SPARCS_2014_compressed.csv.gz')

In [3]:
data

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
0,37.0,F,8,197,Skin and subcutaneous tissue infections,0,NO PROC,90335341.0,NaN,$9546.85
1,37.0,F,3,146,Diverticulosis and diverticulitis,0,NO PROC,90335341.0,NaN,$11462.75
2,37.0,M,1,50,Diabetes mellitus with complications,202,ELECTROCARDIOGRAM,90335341.0,167816.0,$1609.40
3,37.0,F,1,154,Noninfectious gastroenteritis,202,ELECTROCARDIOGRAM,90335341.0,167816.0,$2638.75
4,37.0,F,3,124,Acute and chronic tonsillitis,0,NO PROC,90335341.0,NaN,$3538.25
...,...,...,...,...,...,...,...,...,...,...
2367278,943.0,F,1,245,Syncope,0,NO PROC,156102.0,NaN,$10074.00
2367279,943.0,M,1,149,Biliary tract disease,0,NO PROC,267443.0,NaN,$21252.00
2367280,943.0,F,1,102,Nonspecific chest pain,0,NO PROC,267443.0,NaN,$11673.00
2367281,943.0,F,1,660,Alcohol-related disorders,171,SUTURE SKIN/SUBCUT TISS,267443.0,249597.0,$16722.00
2367282,943.0,M,1,2,Septicemia (except in labor),0,NO PROC,251080.0,NaN,$11637.00

## Format conversion

In [4]:
data.to_numpy()

array([[37.0, 'F', '8', ..., 90335341.0, nan, '$9546.85'],
       [37.0, 'F', '3', ..., 90335341.0, nan, '$11462.75'],
       [37.0, 'M', '1', ..., 90335341.0, 167816.0, '$1609.40'],
       ...,
       [943.0, 'F', '1', ..., 267443.0, nan, '$11673.00'],
       [943.0, 'F', '1', ..., 267443.0, 249597.0, '$16722.00'],
       [943.0, 'M', '1', ..., 251080.0, nan, '$11637.00']], dtype=object)

## Data access

Columns (and rows) have names that you can use to access them

In [5]:
data.columns

Index(['Facility ID', 'Gender', 'Length of Stay', 'CCS Diagnosis Code',
       'CCS Diagnosis Description', 'CCS Procedure Code',
       'CCS Procedure Description', 'Attending Provider License Number',
       'Operating Provider License Number', 'Total Charges'],
      dtype='object')

In [6]:
data.Gender  # get gender column

0          F
1          F
2          M
3          F
4          F
          ..
2367278    F
2367279    M
2367280    F
2367281    F
2367282    M
Name: Gender, Length: 2367283, dtype: object

## Data access

In [7]:
data["CCS Diagnosis Code"][:3] # can't use dot syntax if column name has spaces

0    197
1    146
2     50
Name: CCS Diagnosis Code, dtype: int64

`[]` slices by rows, but *indexes* by column name - must provide range or it interprets the index as a column label.

In [8]:
data[:1]

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
0,37.0,F,8,197,Skin and subcutaneous tissue infections,0,NO PROC,90335341.0,NaN,$9546.85

## No (default) access by number

In [9]:
data[0]

KeyError: 0

## `.iloc`: Position indexing

If you want to reference a pandas data frame with position based indexing, use `.iloc` - works just like `numpy`

In [12]:
data.iloc[3, 0]

37.0

In [13]:
data.iloc[0,:]

Facility ID                                                             37.0
Gender                                                                     F
Length of Stay                                                             8
CCS Diagnosis Code                                                       197
CCS Diagnosis Description            Skin and subcutaneous tissue infections
CCS Procedure Code                                                         0
CCS Procedure Description                                            NO PROC
Attending Provider License Number                                 90335341.0
Operating Provider License Number                                        NaN
Total Charges                                                       $9546.85
Name: 0, dtype: object

Pandas uses NaN to indicate missing data

## `.loc`: Label indexing

You can also index by the label names  

Note that rows are indexed by their named index

In [14]:
data.loc[:3, 'Gender']

0    F
1    F
2    M
3    F
Name: Gender, dtype: object

In [15]:
data.loc[[0,3,5],['CCS Diagnosis Description','CCS Diagnosis Code']]

                 CCS Diagnosis Description  CCS Diagnosis Code
0  Skin and subcutaneous tissue infections                 197
3            Noninfectious gastroenteritis                 154
5                                Influenza                 123

## Row slices

In [16]:
data[10:20]

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
10,37.0,F,3,123,Influenza,0,NO PROC,90335341.0,NaN,$4566.15
11,37.0,M,7,122,Pneumonia (except that caused by tuberculosis ...,202,ELECTROCARDIOGRAM,90335341.0,167816.0,$9822.90
12,37.0,M,3,122,Pneumonia (except that caused by tuberculosis ...,0,NO PROC,90335341.0,NaN,$5063.05
13,37.0,M,2,155,Other gastrointestinal disorders,0,NO PROC,90335341.0,NaN,$3125.75
14,37.0,F,3,122,Pneumonia (except that caused by tuberculosis ...,0,NO PROC,90335341.0,NaN,$5055.45
15,37.0,F,6,127,Chronic obstructive pulmonary disease and bron...,0,NO PROC,90335341.0,NaN,$9734.05
16,37.0,F,4,127,Chronic obstructive pulmonary disease and bron...,0,NO PROC,90335341.0,NaN,$7168.05
17,37.0,F,2,197,Skin and subcutaneous tissue infections,0,NO PROC,90301264.0,NaN,$2812.85
18,37.0,M,3,58,Other nutritional; endocrine; and metabolic di...,0,NO PROC,90335341.0,NaN,$3377.50
19,37.0,F,2,125,Acute bronchitis,0,NO PROC,90335341.0,NaN,$3214.25

## Note: `.loc` indices are *absolute*, not *relative*

In [20]:
data[10:20].iloc[[0,3,5]]

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
10,37.0,F,3,123,Influenza,0,NO PROC,90335341.0,NaN,$4566.15
13,37.0,M,2,155,Other gastrointestinal disorders,0,NO PROC,90335341.0,NaN,$3125.75
15,37.0,F,6,127,Chronic obstructive pulmonary disease and bron...,0,NO PROC,90335341.0,NaN,$9734.05

In [18]:
data[10:20].iloc[[0,3,5]]

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
10,37.0,F,3,123,Influenza,0,NO PROC,90335341.0,NaN,$4566.15
13,37.0,M,2,155,Other gastrointestinal disorders,0,NO PROC,90335341.0,NaN,$3125.75
15,37.0,F,6,127,Chronic obstructive pulmonary disease and bron...,0,NO PROC,90335341.0,NaN,$9734.05

## Boolean Indexing

Just like `numpy` we can index by a boolean array or an array of indices.

In [21]:
data[data.Gender == 'M'][:3]

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
2,37.0,M,1,50,Diabetes mellitus with complications,202,ELECTROCARDIOGRAM,90335341.0,167816.0,$1609.40
6,37.0,M,5,122,Pneumonia (except that caused by tuberculosis ...,0,NO PROC,90335341.0,NaN,$6148.10
7,37.0,M,3,123,Influenza,0,NO PROC,90335341.0,NaN,$4204.15

In [22]:
data.iloc[:,[0,3,5]][:3]

   Facility ID  CCS Diagnosis Code  CCS Procedure Code
0         37.0                 197                   0
1         37.0                 146                   0
2         37.0                  50                 202

## Sorting

In [23]:
data.sort_values(by="Total Charges").head(3)

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
1426998,1439.0,M,1,108,Congestive heart failure; nonhypertensive,0,NO PROC,251948.0,NaN,$0.50
780065,989.0,M,2,657,Mood disorders,218,PSYCHO/PSYCHI EVAL/THER,199003.0,154247.0,$1.00
781531,989.0,F,1,661,Substance-related disorders,0,NO PROC,145418.0,NaN,$1.00

## Is $99,999.65 the most expensive record?

In [24]:
data.sort_values(by="Total Charges",ascending=False).head(3)

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
77722,213.0,F,10,100,Acute myocardial infarction,44,COR ARTERY BYP GRF-CABG,224769.0,224769.0,$99999.65
451015,635.0,F,1,115,Aortic; peripheral; and visceral artery aneurysms,52,AORTIC RESECTION; REPL,232988.0,232988.0,$99999.46
1579047,1456.0,M,12,2,Septicemia (except in labor),157,AMPUTATE LOWER EXTRMITY,258717.0,265448.0,$99998.45

## String methods

Can apply standard string functions to all cells  
This returns the changed value; it does not mutate in place

In [25]:
data['Total Charges'] = data['Total Charges'].str.lstrip('$').astype(float)

The above *overwrites* the previous Total Charges column to be a floating point number instead of a string with a dollar sign.

## Correct sorting

In [26]:
data.sort_values(by="Total Charges",ascending=False).head(3)

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges
967254,1169.0,M,120 +,63,Diseases of white blood cells,64,BONE MARROW TRANSPLANT,198304.0,229870.0,8593455.88
1560003,1456.0,F,120 +,143,Abdominal hernia,86,OTHER HERNIA REPAIR,165181.0,165181.0,6272871.31
957685,1169.0,F,120 +,6,Hepatitis,176,OT ORGAN TRANSPLANTATN,236414.0,183253.0,5745201.42

## Creating new columns

In [27]:
# setting errors='coerce' below will result in NaN values for invalid input
data['Length of Stay'] = pd.to_numeric(data['Length of Stay'], errors='coerce')
data['Length of Stay'] = data['Length of Stay'].fillna(120)

In [28]:
data['Charge per day'] = data['Total Charges']/data['Length of Stay']

In [29]:
data

,Facility ID,Gender,Length of Stay,CCS Diagnosis Code,CCS Diagnosis Description,CCS Procedure Code,CCS Procedure Description,Attending Provider License Number,Operating Provider License Number,Total Charges,Charge per day
0,37.0,F,8.0,197,Skin and subcutaneous tissue infections,0,NO PROC,90335341.0,NaN,9546.85,1193.356250
1,37.0,F,3.0,146,Diverticulosis and diverticulitis,0,NO PROC,90335341.0,NaN,11462.75,3820.916667
2,37.0,M,1.0,50,Diabetes mellitus with complications,202,ELECTROCARDIOGRAM,90335341.0,167816.0,1609.40,1609.400000
3,37.0,F,1.0,154,Noninfectious gastroenteritis,202,ELECTROCARDIOGRAM,90335341.0,167816.0,2638.75,2638.750000
4,37.0,F,3.0,124,Acute and chronic tonsillitis,0,NO PROC,90335341.0,NaN,3538.25,1179.416667
...,...,...,...,...,...,...,...,...,...,...,...
2367278,943.0,F,1.0,245,Syncope,0,NO PROC,156102.0,NaN,10074.00,10074.000000
2367279,943.0,M,1.0,149,Biliary tract disease,0,NO PROC,267443.0,NaN,21252.00,21252.000000
2367280,943.0,F,1.0,102,Nonspecific chest pain,0,NO PROC,267443.0,NaN,11673.00,11673.000000
2367281,943.0,F,1.0,660,Alcohol-related disorders,171,SUTURE SKIN/SUBCUT TISS,267443.0,249597.0,16722.00,16722.000000
2367282,943.0,M,1.0,2,Septicemia (except in labor),0,NO PROC,251080.0,NaN,11637.00,11637.000000

## Error handling

In [30]:
pd.to_numeric('120 +', errors='coerce')

nan

In [31]:
pd.to_numeric('120 +', errors='ignore')

/var/folders/sq/hxhw3k8d6gb7b_r53z39zpfr0000gn/T/ipykernel_32869/2940737626.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  pd.to_numeric('120 +', errors='ignore')

'120 +'

In [32]:
pd.to_numeric('120 +')

ValueError: Unable to parse string "120 +" at position 0

## Group by

Group records that have the same value for a column

In [33]:
data.groupby('Facility ID')

We can then apply an aggregating function to these groups.

In [34]:
# note: make sure mean() is only applied to columns with numerical values, or you will get an error
data.groupby('Facility ID').mean(numeric_only=True).sort_values(by='Total Charges')

,Length of Stay,CCS Diagnosis Code,CCS Procedure Code,Attending Provider License Number,Operating Provider License Number,Total Charges,Charge per day
Facility ID,,,,,,,
377.0,2.670732,121.170732,202.439024,4.664694e+07,4.826434e+07,4060.734024,1614.759785
111.0,3.611111,159.777778,0.000000,1.929986e+05,NaN,4492.587778,1473.003327
37.0,3.162791,123.906977,54.779070,8.298531e+07,7.666251e+06,4939.879651,1628.579552
9250.0,2.203456,205.840173,137.955076,1.082429e+07,1.264187e+07,5618.928860,2497.869519
165.0,4.597884,180.206349,181.920635,2.051072e+05,4.744077e+07,6376.906455,1580.321499
...,...,...,...,...,...,...,...
563.0,6.279619,129.367643,78.085210,2.363745e+05,6.581608e+05,89385.986450,20937.033431
1446.0,5.633545,214.859847,157.190406,3.497396e+05,3.955800e+05,124204.521077,36290.348526
1139.0,8.937250,205.031446,87.044577,3.341266e+05,3.847957e+05,131992.454991,17629.688410
1138.0,38.527005,215.072013,213.108020,1.963923e+05,1.966056e+05,175997.805859,4195.405483
1486.0,61.821429,134.039683,194.801587,1.863599e+05,1.921974e+05,195780.272579,2486.885826

## Example

In [35]:
data.groupby('Gender').mean(numeric_only=True).sort_values(by='Total Charges').loc[:,['Total Charges']]

        Total Charges
Gender
U         9858.198939
F        36867.585805
M        44419.344760

The group by column has become an indexing column.  Need to `reset_index` to convert *index* to *columns*.

In [36]:
data.groupby('Gender').mean(numeric_only=True).sort_values(by='Total Charges').reset_index().loc[:,['Gender','Total Charges']]

  Gender  Total Charges
0      U    9858.198939
1      F   36867.585805
2      M   44419.344760

## Example

In [39]:
data.groupby(['CCS Procedure Description', 'Gender'])['Total Charges'].mean()

CCS Procedure Description  Gender
ABDOMINAL PARACENTESIS     F         56996.536195
                           M         58532.559231
ABORTION (TERM OF PREG)    F         26512.622947
ALCO/DRUG REHAB/DETOX      F         18954.578164
                           M         18187.073614
                                         ...
UPPER GI X-RAY             M         31221.460246
URETERAL CATHETERIZATN     F         36143.329481
                           M         34182.121658
VARI VEIN STRIP;LOW LMB    F         42519.938571
                           M         65763.081875
Name: Total Charges, Length: 446, dtype: float64

## `unstack` pivots a level of the (necessarily hierarchical) index labels

In [40]:
gendercosts = data.groupby(['CCS Procedure Description','Gender'])['Total Charges'].mean().unstack()
gendercosts

Gender                                 F              M   U
CCS Procedure Description
ABDOMINAL PARACENTESIS      56996.536195   58532.559231 NaN
ABORTION (TERM OF PREG)     26512.622947            NaN NaN
ALCO/DRUG REHAB/DETOX       18954.578164   18187.073614 NaN
AMPUTATE LOWER EXTRMITY    100926.639344   92821.328596 NaN
AORTIC RESECTION; REPL     144019.629159  114210.484050 NaN
...                                  ...            ...  ..
UNGROUPABLE                 68101.627500  105811.388636 NaN
UP GASTRO ENDOSC/BIOPSY     42625.453678   43340.006917 NaN
UPPER GI X-RAY              28339.654074   31221.460246 NaN
URETERAL CATHETERIZATN      36143.329481   34182.121658 NaN
VARI VEIN STRIP;LOW LMB     42519.938571   65763.081875 NaN

[233 rows x 3 columns]

In [41]:
genderdiffs = gendercosts.F - gendercosts.M
genderdiffs

CCS Procedure Description
ABDOMINAL PARACENTESIS     -1536.023036
ABORTION (TERM OF PREG)             NaN
ALCO/DRUG REHAB/DETOX        767.504550
AMPUTATE LOWER EXTRMITY     8105.310748
AORTIC RESECTION; REPL     29809.145110
                               ...
UNGROUPABLE               -37709.761136
UP GASTRO ENDOSC/BIOPSY     -714.553239
UPPER GI X-RAY             -2881.806172
URETERAL CATHETERIZATN      1961.207823
VARI VEIN STRIP;LOW LMB   -23243.143304
Length: 233, dtype: float64

In [42]:
genderdiffs.dropna(inplace=True)  #remove rows with NaN, modify genderdiffs in place
genderdiffs

CCS Procedure Description
ABDOMINAL PARACENTESIS     -1536.023036
ALCO/DRUG REHAB/DETOX        767.504550
AMPUTATE LOWER EXTRMITY     8105.310748
AORTIC RESECTION; REPL     29809.145110
APPENDECTOMY                 209.527573
                               ...
UNGROUPABLE               -37709.761136
UP GASTRO ENDOSC/BIOPSY     -714.553239
UPPER GI X-RAY             -2881.806172
URETERAL CATHETERIZATN      1961.207823
VARI VEIN STRIP;LOW LMB   -23243.143304
Length: 202, dtype: float64

In [43]:
genderdiffs.sort_values().head(5)

CCS Procedure Description
EXTRA CIRC AUX OPEN HRT   -69453.636115
DX PRCS ON EYE            -63462.345439
SWAN-GANZ CATH MONITOR    -46738.846837
PRCS ON SPLEEN            -46219.301962
CORNEAL TRANSPLANT        -45028.501148
dtype: float64

In [44]:
genderdiffs.sort_values().tail(5)

CCS Procedure Description
LENS & CATARACT PRCS       35378.240602
OT INTRAOCULAR THER PRC    35907.146236
BONE MARROW TRANSPLANT     37066.859998
DES LES RETINA/CHOROID     52461.621223
CORONARY THROMBOLYSIS      87870.550000
dtype: float64

## Combining DataFrames

`pd.concat` concatenates rows (i.e., default axis=0) while merging columns with the same name

In [45]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df2 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)

In [46]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [47]:
df2

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [48]:
pd.concat([df1,df2])

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

## Join

You can **join** two tables **on** a specific column (or columns)  
Rows that has the same value (or _key_) in that column will be combined

In [49]:
left = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                     "A": ["A0", "A1", "A2", "A3"],
                     "B": ["B0", "B1", "B2", "B3"],})


right = pd.DataFrame({"key": [ "K1", "K2", "K4"],
                      "C": ["C1", "C2", "C4"],
                      "D": ["D1", "D2", "D4"],})

In [50]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [51]:
right

  key   C   D
0  K1  C1  D1
1  K2  C2  D2
2  K4  C4  D4

## Inner join

Key must exist in both tables

In [52]:
pd.merge(left,right,on='key',how='inner')

  key   A   B   C   D
0  K1  A1  B1  C1  D1
1  K2  A2  B2  C2  D2

## Outer join

Key can exist in either table

In [53]:
pd.merge(left,right,on='key',how='outer')

  key    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1   C1   D1
2  K2   A2   B2   C2   D2
3  K3   A3   B3  NaN  NaN
4  K4  NaN  NaN   C4   D4

# Left (right) join

Key must exist in left (right) table

In [54]:
pd.merge(left, right, on='key', how='left')

  key   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN

In [55]:
pd.merge(left, right, on='key', how='right')

  key    A    B   C   D
0  K1   A1   B1  C1  D1
1  K2   A2   B2  C2  D2
2  K4  NaN  NaN  C4  D4

## Questions

Download: https://mscbio2025-2025.github.io/files/SPARCS_2014_compressed.csv.gz

* How many data records are there?  
* How many coronary bypasses are there?  
* What is the average cost? Standard deviation?  
* What is the most common diagnosis that leads to a coronary bypass?  
* What percent of people with that diagnosis get a coronary bypass?  
* What are the facilities whose average cost for this operation is in the top 10%? Bottom 10%?  
* How correlated is the length of stay to the cost?  
* Is the percentage of people who go to these facilities with the most common diagnosis and receive a coronary bypass significantly different between these two groups?  
* What about knee replacements?  
* How well can a decision tree predict the cost of the operation?  What are the most important features?

## For next time

Python packages for sequence analysis.

In [ ]:
import csv, collections
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
import pandas as pd
data = pd.read_csv('../files/SPARCS_2014_compressed.csv.gz')

In [ ]:
data.columns

In [ ]:
#remove dollar sign
data['Total Charges'] = data['Total Charges'].str.lstrip('$').astype(float)

In [ ]:
sorted(pd.unique(data['CCS Procedure Description']))

In [ ]:
proccodes = {(code,desc) for (code,desc) in data.loc[:,('CCS Procedure Code', 'CCS Procedure Description')].values}

In [ ]:
diagcodes = {(code,desc) for (code,desc) in data.loc[:,('CCS Diagnosis Code', 'CCS Diagnosis Description')].values}

In [ ]:
proccodes

In [ ]:
P = 44  #proc number we're interested in

In [ ]:
procrows = data[data['CCS Procedure Description'] == 'COR ARTERY BYP GRF-CABG']
len(procrows)

In [ ]:
plt.hist(procrows['Total Charges'],bins=100);
plt.xlim(0,1000000)

In [ ]:
procrows['Total Charges'].mean()

In [ ]:
procrows.groupby('CCS Diagnosis Description').count()

In [ ]:
diagcnts = procrows['CCS Diagnosis Description'].value_counts()
diagcnts

In [ ]:
D = diagcnts.index[0] # the code is the row name
D

In [ ]:
diagrows = data[data['CCS Diagnosis Description'] == D]
diagrows

In [ ]:
len(diagrows[diagrows['CCS Procedure Description'] == 'COR ARTERY BYP GRF-CABG'])/len(diagrows)

In [ ]:
#let's calculate average cost per facility
aves = procrows.loc[:,('Facility ID','Total Charges')].groupby('Facility ID').mean()
aves

In [ ]:
procrows = procrows.copy()
procrows['Length of Stay'] = pd.to_numeric(procrows['Length of Stay'],errors='coerce')

In [ ]:
procrows.dropna(inplace=True)

In [ ]:
plt.scatter(procrows['Total Charges'],procrows['Length of Stay'])

In [ ]:
np.corrcoef(procrows['Total Charges'],procrows['Length of Stay'])

In [ ]:
plt.hist(aves.values,bins=20)

In [ ]:
avesorted = aves.sort_values(by='Total Charges')
avesorted

In [ ]:
tenth = int(len(avesorted)/10)
top10 = avesorted.iloc[-tenth:]
bottom10 = avesorted.iloc[:tenth]

In [ ]:
top10

In [ ]:
topprocs = procrows[procrows['Facility ID'].isin(top10.index) & (procrows['CCS Diagnosis Description'] == D)]
bottomprocs = procrows[procrows['Facility ID'].isin(bottom10.index) & (procrows['CCS Diagnosis Description'] == D)]

topdiags = diagrows[diagrows['Facility ID'].isin(top10.index)]
bottomdiags = diagrows[diagrows['Facility ID'].isin(bottom10.index)]

In [ ]:
len(topprocs)/float(len(topdiags))

In [ ]:
len(bottomprocs)/float(len(bottomdiags))

In [ ]:
topdiags['CCS Procedure Description'].value_counts()/len(topdiags)

In [ ]:
bottomdiags['CCS Procedure Description'].value_counts()/len(bottomdiags)

Train a predictive model for cost.

In [ ]:
X = procrows.drop(['Total Charges'],axis=1)
Y = procrows['Total Charges']

In [ ]:
import sklearn
from sklearn import tree, ensemble,preprocessing, feature_extraction

In [ ]:
X_dict = list(X.astype(np.str).T.to_dict().values())

In [ ]:
X_dict

In [ ]:
dvec = feature_extraction.DictVectorizer()
vect = dvec.fit_transform(X_dict)

In [ ]:
print(vect[0])

In [ ]:
dvec.get_feature_names()[793]

In [ ]:
from sklearn import metrics

In [ ]:
m = tree.DecisionTreeRegressor()
dtree = m.fit(vect,Y)
metrics.r2_score(dtree.predict(vect),Y)

In [ ]:
plt.plot(dtree.predict(vect),Y,'o',alpha=.1)
plt.xlabel("Prediction")
plt.ylabel("Actual")

In [ ]:
from sklearn import model_selection

gm = model_selection.GridSearchCV(m, {'max_depth':[None,2,3,4,6,8,10,15,20]},scoring='r2')
gres = gm.fit(vect,Y)

In [ ]:
gres.best_score_

In [ ]:
gres.best_params_

In [ ]:
from IPython.display import Image  
import io, os, pydotplus as pydot

dot_data = io.StringIO() 
tree.export_graphviz(gres.best_estimator_, out_file=dot_data,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph.set_graphviz_executables(paths={"dot": os.path.join(*["D:","Graphviz","bin", "dot.exe"]),
                                      "twopi": os.path.join(*["D:","Graphviz","bin", "twopi.exe"]),
                                      "neato": os.path.join(*["D:","Graphviz","bin", "neato.exe"]),
                                      "circo": os.path.join(*["D:","Graphviz","bin", "circo.exe"]),
                                      "fdp": os.path.join(*["D:","Graphviz","bin", "fdp.exe"])})

In [ ]:
Image(graph.create_png())

In [ ]:
dvec.get_feature_names()[523]

In [ ]:
dvec.get_feature_names()[406]

In [ ]:
diagcodes

In [ ]:
forest = ensemble.RandomForestRegressor()
m = forest.fit(vect,Y)

In [ ]:
metrics.r2_score(m.predict(vect),Y)

In [ ]:
gm = model_selection.GridSearchCV(m, {'max_depth':[None,2,3,4,6,8,10,15,20]},scoring='r2')
gres = gm.fit(vect,Y)

In [ ]:
gres.best_score_

In [ ]:
gres.best_params_

In [ ]:
gres.best_estimator_.feature_importances_.argmax()

In [ ]:
dvec.get_feature_names()[137]